#server.servlet.context-path=/  应用上下文
#server.address 服务器IP绑定地址
#server.session.timeout 会话过期时间，单位秒
#server.error.path 服务器出错后的处理路径/error
#server.port 监听端口
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot2_js?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
  thymeleaf:
    #关闭 Thymeleaf 的缓存开发过程中无需重启
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
  banner:
    charset: UTF-8
    location: classpath:banner.txt
#    image:
#      location: classpath:banner.gif
#      width: 76
#      height: 76
#      margin: 2
  profiles:
    active: default
logging:
  level:
    root: info
    org:
      springframework: info
    com:
      cooperative: debug
#  file: my.log
#  pattern:
#    console: %level %date{HH:mm:ss} %logger{20}.%M %L :%m%n
#    file: %level %date{ISO8601} [%thread]  %logger{20}.%M %L :%m%n

wxpayconfig:
  #商户应用appId
  appID:
  #商户ID
  mchID:
  #小程序 appSecret
  appSecret:
  #商户key：api秘钥（32位）
  key:
  #回调接口
  notify_url: https://www.xxx.com/api/wxMiniCallBack
  refund_url: https://www.xxx.com/api/wxMiniRefundCallBack
  #证书路径 classpath:apiclient_cert.p12
  certPath: 